---
kind: pipeline
type: docker
name: prepare

steps:
- name: docker
  image: docker
  commands:
  - docker build -t portainer-api-drone:build . -f Dockerfile-dev
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock

volumes:
- name: docker-sock
  host: { path: /var/run/docker.sock }

---
kind: pipeline
type: docker
name: analyze

steps:
- name: psalm
  image: portainer-api-drone:build
  commands:
  - mv /www/vendor vendor
  - vendor/bin/psalm --show-info=true
depends_on:
- prepare
